# Generated by Django 3.0.2 on 2020-05-14 23:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import espectro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('visualizador_nacional', 'Visualizador Nacional'), ('permisionario', 'Permisionario')),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Sistema')),
                ('enlace', models.CharField(max_length=200)),
                ('accion', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100, unique=True)),
                ('valor_pago_licencia', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('meses_diferir_pago', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, 'El valor debe ser mayor 0')])),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_notificacion', models.CharField(max_length=20, unique=True)),
                ('fecha_notificacion', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0.1, message='El valor debe ser mayor 0')])),
                ('archivo_pago', models.FileField(blank=True, null=True, upload_to=espectro.models.upload_path_pago)),
                ('division_territorial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.DivisionTerritorial')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sistema', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Sistema/Expediente')),
                ('enlace', models.CharField(max_length=200, unique=True)),
                ('esta_en_uso', models.BooleanField(default=False)),
                ('division_territorial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.DivisionTerritorial', verbose_name='División Territorial')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='espectro.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sistema', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField()),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
                ('archivo_solicitud', models.FileField(blank=True, max_length=200, null=True, upload_to=espectro.models.upload_path_solicitud)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espectro.Sistema')),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='espectro.TipoSolicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.Municipio')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espectro.Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='PagoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(max_length=20)),
                ('enlace', models.CharField(max_length=100)),
                ('tipo_sistema', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0.1, message='El valor debe ser mayor 0')], verbose_name='Valor Sistema')),
                ('valor_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio_pago', models.DateField()),
                ('fecha_fin_pago', models.DateField()),
                ('meses_diferir', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='El valor debe ser mayor 0')])),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espectro.Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('archivo_licencia', models.FileField(blank=True, max_length=200, null=True, upload_to=espectro.models.upload_path_licencia)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espectro.Solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='espectro.TipoSistema'),
        ),
    ]
