# Generated by Django 3.0.2 on 2020-01-27 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAsociado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DivisionTerritorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('identificativo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GInformacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ginfo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.CentroAsociado')),
                ('ginfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.GInformacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion', models.CharField(max_length=100, unique=True)),
                ('ginfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.GInformacion')),
            ],
        ),
        migrations.CreateModel(
            name='CentroPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('division_territorial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.DivisionTerritorial')),
            ],
        ),
        migrations.AddField(
            model_name='centroasociado',
            name='centro_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.CentroPrincipal'),
        ),
        migrations.AddField(
            model_name='centroasociado',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.Municipio'),
        ),
    ]
